CREATE DATABASE IF NOT EXISTS biblioteca;
USE biblioteca;

CREATE TABLE libros (
    id INT AUTO_INCREMENT PRIMARY KEY,
    titulo VARCHAR(255) NOT NULL,
    autor VARCHAR(255) NOT NULL,
    anio_publicacion INT NOT NULL,
    genero VARCHAR(100) NOT NULL
);

INSERT INTO libros (titulo, autor, anio_publicacion, genero) VALUES
('Cien años de soledad', 'Gabriel García Márquez', 1967, 'Realismo mágico'),
('Don Quijote de la Mancha', 'Miguel de Cervantes', 1605, 'Novela'),
('1984', 'George Orwell', 1949, 'Distopía'),
('El Principito', 'Antoine de Saint-Exupéry', 1943, 'Fábula'),
('Rayuela', 'Julio Cortázar', 1963, 'Novela'),
('Fahrenheit 451', 'Ray Bradbury', 1953, 'Ciencia ficción'),
('Crónica de una muerte anunciada', 'Gabriel García Márquez', 1981, 'Novela'),
('Los miserables', 'Victor Hugo', 1862, 'Novela histórica'),
('Moby-Dick', 'Herman Melville', 1851, 'Aventura'),
('El Gran Gatsby', 'F. Scott Fitzgerald', 1925, 'Novela'),
('Orgullo y prejuicio', 'Jane Austen', 1813, 'Romance'),
('La metamorfosis', 'Franz Kafka', 1915, 'Ficción'),
('Drácula', 'Bram Stoker', 1897, 'Terror'),
('El nombre de la rosa', 'Umberto Eco', 1980, 'Misterio'),
('La sombra del viento', 'Carlos Ruiz Zafón', 2001, 'Ficción histórica'),
('It', 'Stephen King', 1986, 'Terror'),
('Los juegos del hambre', 'Suzanne Collins', 2008, 'Distopía'),
('Dune', 'Frank Herbert', 1965, 'Ciencia ficción'),
('El código Da Vinci', 'Dan Brown', 2003, 'Misterio'),
('Los pilares de la Tierra', 'Ken Follett', 1989, 'Ficción histórica'),
('El Hobbit', 'J.R.R. Tolkien', 1937, 'Fantasía'),
('El Señor de los Anillos', 'J.R.R. Tolkien', 1954, 'Fantasía'),
('Crimen y castigo', 'Fiódor Dostoyevski', 1866, 'Novela psicológica'),
('El retrato de Dorian Gray', 'Oscar Wilde', 1890, 'Ficción gótica'),
('En busca del tiempo perdido', 'Marcel Proust', 1913, 'Ficción'),
('La Odisea', 'Homero', -700, 'Épica'),
('Los hombres me explican cosas', 'Rebecca Solnit', 2014, 'Ensayo'),
('El Aleph', 'Jorge Luis Borges', 1949, 'Cuento'),
('Bajo la misma estrella', 'John Green', 2012, 'Juvenil'),
('Percy Jackson y el ladrón del rayo', 'Rick Riordan', 2005, 'Fantasía'),
('La casa de los espíritus', 'Isabel Allende', 1982, 'Realismo mágico'),
('El alquimista', 'Paulo Coelho', 1988, 'Ficción filosófica'),
('El arte de la guerra', 'Sun Tzu', -500, 'Estrategia'),
('El perfume', 'Patrick Süskind', 1985, 'Ficción histórica'),
('El extraño caso del Dr. Jekyll y Mr. Hyde', 'Robert Louis Stevenson', 1886, 'Misterio'),
('Hamlet', 'William Shakespeare', 1603, 'Tragedia'),
('Macbeth', 'William Shakespeare', 1606, 'Tragedia'),
('Cumbres Borrascosas', 'Emily Brontë', 1847, 'Romance'),
('Las crónicas de Narnia', 'C.S. Lewis', 1950, 'Fantasía'),
('Los detectives salvajes', 'Roberto Bolaño', 1998, 'Novela'),
('El túnel', 'Ernesto Sabato', 1948, 'Novela psicológica'),
('Matar a un ruiseñor', 'Harper Lee', 1960, 'Novela'),
('Las mil y una noches', 'Anónimo', 800, 'Cuento'),
('La isla del tesoro', 'Robert Louis Stevenson', 1883, 'Aventura'),
('Frankenstein', 'Mary Shelley', 1818, 'Terror'),
('Los hermanos Karamázov', 'Fiódor Dostoyevski', 1880, 'Novela psicológica'),
('Guerra y paz', 'León Tolstói', 1869, 'Novela histórica'),
('Memorias de una geisha', 'Arthur Golden', 1997, 'Ficción histórica'),
('El castillo', 'Franz Kafka', 1926, 'Ficción existencialista'),
('La insoportable levedad del ser', 'Milan Kundera', 1984, 'Filosofía'),
('El laberinto de los espíritus', 'Carlos Ruiz Zafón', 2016, 'Ficción histórica'),
('Papá Goriot', 'Honoré de Balzac', 1835, 'Realismo'),
('Anna Karénina', 'León Tolstói', 1877, 'Novela'),
('Los viajes de Gulliver', 'Jonathan Swift', 1726, 'Aventura'),
('El médico', 'Noah Gordon', 1986, 'Ficción histórica'),
('Siddhartha', 'Hermann Hesse', 1922, 'Filosofía'),
('La naranja mecánica', 'Anthony Burgess', 1962, 'Ciencia ficción');
